# put common definitions in here

#Compile
CC	= g++

#Compile Flags
CFLAGS = -Wall -o0 -fno-inline -g -std=c++11 -fpic -Wfatal-errors

#Compile shared Lib flags
CSHAREDFLAGS= -shared

#Shared lib linking flags
SHAREDLDFLAGS= -Wl,-rpath,../bin/lib

#Header files
INCLUDES= -I./../include

#Liberary folders
LFLAGS = -L./../bin/lib

#Liberary names
LIBS=
##-lArduino -lRobotMath

OBJECTFOLDER=

RM= rm -rf

MKDIR_P = mkdir -p

LINK = ln -fsv

.SILENT :


