# put common definitions in here

INCLUDEFOLDER=./include
OBJECTFOLDER=./bin/objects
LIBFOLDER=./bin/lib

#Compile
CC	= g++

#Compile Flags
CFLAGS = -Wall -o0 -fno-inline -g -std=c++11 -fpic -Wfatal-errors

#Compile shared Lib flags
CSHAREDFLAGS= -shared

#Shared lib linking flags
SHAREDLDFLAGS= -Wl,-rpath,$(LIBFOLDER)

#Header files
INCLUDES= -I./$(INCLUDEFOLDER)

#Liberary folders
LFLAGS = -L./$(LIBFOLDER)

#Liberary names
LIBS=

RM= rm -rf

MKDIR_P = mkdir -p

LINK = ln -fsv

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) -c $<  -o $@
	$(LINK) $@ $(OBJECTFOLDER)$@

clean: 
	$(RM) *.o
	$(RM) *.so
	$(RM) *$(MAIN)*
	$(RM) $(DEBUG)
	$(RM) $(addprefix $(OBJECTFOLDER),$(OBJS))
	$(RM) $(addprefix $(LIBFOLDER),*$(MAIN)*)
  

.SILENT :


