# 'make depend' uses makedepend to automatically generate dependencies 
#               (dependencies are added to end of Makefile)
# 'make'        build executable file 'mycc'
# 'make clean'  removes all .o and executable files
#


TOROOT= ..

# define the C source files
SRCS= pugixml.cpp

LIBS=

# define the executable file 
MAIN = PugiXML
DEBUG = debug

include ../Makefile.config

